# Site
repository: michaelsdahl/michaelsdahl.github.io
favicon: images/favicon.ico

# Personal info
name: Michael S. Dahl
title: Professor, Board Member
email: md@msdahl.com
website: www.msdahl.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: msdahl
github_username:  michaelsdahl
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: msdahl
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: About me
about_profile_image: images/profile_msd.jpg
about_content: | # this will include new lines to allow paragraphs
  Text here
  
  I am most skilled in: <mark>Baking Pizza</mark>

# Projects Section
projects_title: Boards

# Experience Section
experience_title: Employment

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
